server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wmsdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: 自己数据库的用户名
    password: 自己的密码
