server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wmsdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456